# Generated by Django 4.0.1 on 2023-05-09 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_alter_message_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='fact',
        ),
    ]
