# Generated by Django 4.0.1 on 2023-05-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_rename_message_message_fact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='email',
            new_name='reciever',
        ),
        migrations.RemoveField(
            model_name='message',
            name='name',
        ),
        migrations.AddField(
            model_name='message',
            name='emailAddress',
            field=models.EmailField(default='abe@gmail.com', max_length=255),
        ),
    ]
